// ============================================================
// ArxMint — Merchant Config Generator
// Mirrors the logic in scripts/merchant-init.sh for browser use.
// ============================================================

export type PaymentMethod = "lightning" | "cashu" | "both";

function toSlug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function generateMerchantEnv(
  name: string,
  methods: PaymentMethod[],
  domain: string
): string {
  const slug = toSlug(name || "my-bitcoin-store");
  const resolvedDomain = domain.trim() || `${slug}.arxmint.com`;
  const enableCashu = methods.includes("cashu") || methods.includes("both");
  const enableOnchain = false; // on-chain reserved for CLI full mode

  return `# ArxMint Merchant Node — generated by arxmint.com/deploy
# NEVER commit this file to version control.

MERCHANT_NAME="${name}"
MERCHANT_SLUG="${slug}"
MERCHANT_DOMAIN="${resolvedDomain}"

# Bitcoin network (testnet | signet | bitcoin)
# Change to 'bitcoin' when ready for mainnet real sats.
BITCOIN_NETWORK=testnet

# Cashu ecash mint private key — BACK THIS UP
# Losing this key means ecash wallet recovery is impossible.
# Generate with: openssl rand -hex 32
CASHU_PRIVATE_KEY=<run: openssl rand -hex 32>

# LND macaroon root key
MACAROON_ROOT_KEY=<run: openssl rand -hex 32>

# ArxMint web app session secret
NEXTAUTH_SECRET=<run: openssl rand -base64 32>

# Features
ENABLE_CASHU=${enableCashu}
ENABLE_ONCHAIN=${enableOnchain}
`;
}

export function generateMerchantCompose(
  name: string,
  methods: PaymentMethod[],
  domain: string
): string {
  const slug = toSlug(name || "my-bitcoin-store");
  const resolvedDomain = domain.trim() || `${slug}.arxmint.com`;
  const enableCashu = methods.includes("cashu") || methods.includes("both");

  const cashuService = enableCashu
    ? `
  cashu-mint:
    image: cashubtc/nutshell:latest
    container_name: ${slug}-cashu
    restart: unless-stopped
    environment:
      - MINT_BACKEND_BOLT11_SAT=LndRestWallet
      - MINT_LND_REST_ENDPOINT=https://lnd:8080
      - MINT_LND_REST_CERT=/root/.lnd/tls.cert
      - MINT_LND_REST_MACAROON=/root/.lnd/data/chain/bitcoin/testnet/admin.macaroon
      - MINT_LISTEN_HOST=0.0.0.0
      - MINT_LISTEN_PORT=3338
      - MINT_PRIVATE_KEY=\${CASHU_PRIVATE_KEY}
    ports:
      - "3338:3338"
    volumes:
      - lnd-data:/root/.lnd:ro
      - cashu-data:/app/data
    depends_on:
      - lnd
    networks:
      - merchant
`
    : "";

  const cashuVolume = enableCashu ? "\n  cashu-data:" : "";

  return `# ArxMint Merchant Node — ${name}
# Generated by arxmint.com/deploy
# Run: docker compose -f docker-compose.merchant.yml up -d

services:

  lnd:
    image: lightninglabs/lnd:v0.18.0-beta
    container_name: ${slug}-lnd
    restart: unless-stopped
    command: >
      lnd
      --bitcoin.active
      --bitcoin.testnet
      --bitcoin.node=neutrino
      --neutrino.addpeer=faucet.lightning.community
      --rpclisten=0.0.0.0:10009
      --restlisten=0.0.0.0:8080
      --tlsextradomain=lnd
      --accept-keysend
      --db.backend=sqlite
    ports:
      - "9735:9735"
      - "10009:10009"
      - "8080:8080"
    volumes:
      - lnd-data:/root/.lnd
    networks:
      - merchant

  arxmint:
    image: ghcr.io/arxmint/arxmint:latest
    container_name: ${slug}-app
    restart: unless-stopped
    env_file:
      - .env.merchant
    environment:
      - LND_REST_ENDPOINT=https://lnd:8080
      - LND_TLS_CERT_PATH=/root/.lnd/tls.cert
      - LND_MACAROON_PATH=/root/.lnd/data/chain/bitcoin/testnet/admin.macaroon
    ports:
      - "3000:3000"
    volumes:
      - lnd-data:/root/.lnd:ro
    depends_on:
      - lnd
    networks:
      - merchant
${cashuService}
  # Optional: Cloudflare Tunnel for public reachability.
  # Set CF_TUNNEL_TOKEN in .env.merchant to activate.
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ${slug}-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=\${CF_TUNNEL_TOKEN:-}
    networks:
      - merchant
    profiles:
      - tunnel

volumes:
  lnd-data:${cashuVolume}

networks:
  merchant:
    driver: bridge

# Checkout page: https://${resolvedDomain}/pay/${slug}
`;
}
