import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { db } from "@/lib/db";

type Params = {
  params: Promise<{ id: string }>;
};

export async function GET(
  _req: Request,
  { params }: Params
) {
  const { id } = await params;

  const invoice = await db.invoice.findUnique({
    where: { id },
    include: {
      lineItems: {
        orderBy: { sortOrder: "asc" },
      },
    },
  });

  if (!invoice) {
    return new Response("Invoice not found", { status: 404 });
  }

  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 842]); // A4
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const orange = rgb(0.97, 0.58, 0.1); // btc-orange #F7931A
  const black = rgb(0, 0, 0);
  const gray = rgb(0.45, 0.45, 0.45);

  // Header
  page.drawText("INVOICE", {
    x: 50,
    y: 780,
    size: 28,
    font: fontBold,
    color: orange,
  });

  const shortId = invoice.invoiceNumber || invoice.id.slice(-8).toUpperCase();
  page.drawText(`#${shortId}`, {
    x: 50,
    y: 748,
    size: 13,
    font,
    color: gray,
  });

  // Status badge
  page.drawText(`Status: ${invoice.status.toUpperCase()}`, {
    x: 400,
    y: 780,
    size: 11,
    font: fontBold,
    color: invoice.status === "paid" ? rgb(0.13, 0.7, 0.37) : orange,
  });

  // Divider line
  page.drawLine({
    start: { x: 50, y: 735 },
    end: { x: 545, y: 735 },
    thickness: 1,
    color: rgb(0.85, 0.85, 0.85),
  });

  // From / To
  page.drawText("FROM", { x: 50, y: 715, size: 9, font: fontBold, color: gray });
  page.drawText(invoice.fromOrgName ?? invoice.fromOrgId, {
    x: 50,
    y: 700,
    size: 12,
    font,
    color: black,
  });

  page.drawText("TO", { x: 300, y: 715, size: 9, font: fontBold, color: gray });
  page.drawText(invoice.toOrgName ?? invoice.toOrgId, {
    x: 300,
    y: 700,
    size: 12,
    font,
    color: black,
  });

  // Due date
  const dueDateStr = invoice.dueDate
    ? new Date(invoice.dueDate).toISOString().slice(0, 10)
    : "Upon receipt";
  page.drawText(`Due: ${dueDateStr}`, { x: 50, y: 678, size: 11, font, color: gray });

  // Line items table header
  page.drawLine({
    start: { x: 50, y: 655 },
    end: { x: 545, y: 655 },
    thickness: 1,
    color: rgb(0.85, 0.85, 0.85),
  });

  page.drawText("DESCRIPTION", { x: 50, y: 640, size: 9, font: fontBold, color: gray });
  page.drawText("QTY", { x: 340, y: 640, size: 9, font: fontBold, color: gray });
  page.drawText("UNIT", { x: 390, y: 640, size: 9, font: fontBold, color: gray });
  page.drawText("TOTAL", { x: 470, y: 640, size: 9, font: fontBold, color: gray });

  page.drawLine({
    start: { x: 50, y: 632 },
    end: { x: 545, y: 632 },
    thickness: 0.5,
    color: rgb(0.9, 0.9, 0.9),
  });

  let y = 616;
  const currency = invoice.currency === "BTC" ? "sats" : "¢";

  for (const item of invoice.lineItems) {
    const desc =
      item.description.length > 45
        ? item.description.slice(0, 42) + "..."
        : item.description;

    page.drawText(desc, { x: 50, y, size: 11, font, color: black });
    page.drawText(String(item.quantity), { x: 340, y, size: 11, font, color: black });
    page.drawText(`${item.unitAmountMinor} ${currency}`, { x: 390, y, size: 11, font, color: black });
    page.drawText(`${item.totalAmountMinor} ${currency}`, { x: 470, y, size: 11, font, color: black });
    y -= 22;
  }

  // Total row
  page.drawLine({
    start: { x: 350, y: y - 4 },
    end: { x: 545, y: y - 4 },
    thickness: 1,
    color: rgb(0.85, 0.85, 0.85),
  });

  page.drawText("TOTAL", { x: 350, y: y - 22, size: 12, font: fontBold, color: black });
  page.drawText(`${invoice.totalMinor} ${currency}`, {
    x: 470,
    y: y - 22,
    size: 13,
    font: fontBold,
    color: orange,
  });

  // Footer
  page.drawText("Generated by ArxMint · arxmint.com", {
    x: 50,
    y: 30,
    size: 8,
    font,
    color: rgb(0.7, 0.7, 0.7),
  });

  const pdfBytes = await pdfDoc.save();
  const filename = `invoice-${shortId}.pdf`;

  return new Response(pdfBytes.buffer as ArrayBuffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Content-Length": String(pdfBytes.length),
    },
  });
}
