#!/usr/bin/env bash
# ============================================================
# ArxMint — Merchant Node Initializer
# 3 questions → .env + docker-compose.merchant.yml
# Usage: bash scripts/merchant-init.sh
#        curl -fsSL https://arxmint.com/scripts/merchant-init.sh | bash
# ============================================================

set -euo pipefail

ENV_FILE=".env.merchant"
COMPOSE_FILE="docker-compose.merchant.yml"

echo "========================================"
echo " ArxMint — Merchant Node Setup"
echo " Financial privacy as a human right."
echo "========================================"
echo ""

# ── Preflight: Docker check ──────────────────────────────────
if ! command -v docker &>/dev/null; then
  echo "ERROR: Docker is not installed."
  echo ""
  echo "Install Docker first:"
  echo "  https://docs.docker.com/engine/install/"
  exit 1
fi

if ! docker compose version &>/dev/null 2>&1; then
  echo "ERROR: 'docker compose' (v2) is not available."
  echo "Upgrade Docker Desktop or install the compose plugin."
  exit 1
fi

# ── Idempotency guard ────────────────────────────────────────
if [ -f "$ENV_FILE" ] || [ -f "$COMPOSE_FILE" ]; then
  echo "Existing config detected:"
  [ -f "$ENV_FILE" ]     && echo "  - $ENV_FILE"
  [ -f "$COMPOSE_FILE" ] && echo "  - $COMPOSE_FILE"
  echo ""
  printf "Re-running will overwrite these files. Continue? [y/N] "
  read -r REPLY
  echo ""
  if [[ ! "$REPLY" =~ ^[Yy]$ ]]; then
    echo "Aborted. Your existing config was not changed."
    exit 0
  fi
fi

# ── Question 1: Merchant name ────────────────────────────────
echo "Question 1 of 3"
printf "What is your merchant name? "
read -r MERCHANT_NAME
MERCHANT_NAME="${MERCHANT_NAME:-My Bitcoin Store}"

# Derive a slug: lowercase, replace spaces/special chars with hyphens
MERCHANT_SLUG=$(echo "$MERCHANT_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/-\+/-/g' | sed 's/^-//' | sed 's/-$//')
echo ""

# ── Question 2: Payment methods ──────────────────────────────
echo "Question 2 of 3"
echo "What payment methods do you want to accept?"
echo "  [1] lightning          — Lightning Network (recommended)"
echo "  [2] lightning + cashu  — Lightning + private ecash (default)"
echo "  [3] all                — Lightning + Cashu + on-chain Bitcoin"
printf "Choice [1/2/3, default 2]: "
read -r PAY_CHOICE
PAY_CHOICE="${PAY_CHOICE:-2}"
echo ""

case "$PAY_CHOICE" in
  1)
    ENABLE_CASHU=false
    ENABLE_ONCHAIN=false
    PAYMENT_LABEL="Lightning"
    ;;
  3)
    ENABLE_CASHU=true
    ENABLE_ONCHAIN=true
    PAYMENT_LABEL="Lightning + Cashu + On-chain"
    ;;
  *)
    ENABLE_CASHU=true
    ENABLE_ONCHAIN=false
    PAYMENT_LABEL="Lightning + Cashu"
    ;;
esac

# ── Question 3: Domain ───────────────────────────────────────
echo "Question 3 of 3"
printf "What domain/hostname will this run on? [localhost]: "
read -r DOMAIN
DOMAIN="${DOMAIN:-localhost}"
echo ""

# ── Generate secrets ─────────────────────────────────────────
if ! command -v openssl &>/dev/null; then
  echo "ERROR: openssl is not installed. Required for secret generation."
  echo "  Ubuntu/Debian: sudo apt install openssl"
  echo "  macOS:         brew install openssl"
  exit 1
fi

CASHU_PRIVATE_KEY=$(openssl rand -hex 32)
MACAROON_ROOT_KEY=$(openssl rand -hex 32)
NEXTAUTH_SECRET=$(openssl rand -base64 32)

mask() { local val="$1"; echo "${val:0:4}****"; }

# ── Write .env.merchant ──────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# ArxMint Merchant Node — generated by merchant-init.sh
# NEVER commit this file to version control.

MERCHANT_NAME="${MERCHANT_NAME}"
MERCHANT_SLUG="${MERCHANT_SLUG}"
MERCHANT_DOMAIN="${DOMAIN}"

# Bitcoin network (testnet | signet | bitcoin)
# Change to 'bitcoin' when ready for mainnet real sats.
BITCOIN_NETWORK=testnet

# Cashu ecash mint private key — BACK THIS UP
# Losing this key means wallet recovery is impossible.
CASHU_PRIVATE_KEY=${CASHU_PRIVATE_KEY}

# LND macaroon root key
MACAROON_ROOT_KEY=${MACAROON_ROOT_KEY}

# ArxMint web app session secret
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# Features
ENABLE_CASHU=${ENABLE_CASHU}
ENABLE_ONCHAIN=${ENABLE_ONCHAIN}
EOF

echo "  Created $ENV_FILE"

# ── Write docker-compose.merchant.yml ───────────────────────
CASHU_SERVICE=""
if [ "$ENABLE_CASHU" = "true" ]; then
  CASHU_SERVICE='
  cashu-mint:
    image: cashubtc/nutshell:latest
    container_name: '${MERCHANT_SLUG}'-cashu
    restart: unless-stopped
    environment:
      - MINT_BACKEND_BOLT11_SAT=LndRestWallet
      - MINT_LND_REST_ENDPOINT=https://lnd:8080
      - MINT_LND_REST_CERT=/root/.lnd/tls.cert
      - MINT_LND_REST_MACAROON=/root/.lnd/data/chain/bitcoin/${BITCOIN_NETWORK:-testnet}/admin.macaroon
      - MINT_LISTEN_HOST=0.0.0.0
      - MINT_LISTEN_PORT=3338
      - MINT_PRIVATE_KEY=${CASHU_PRIVATE_KEY}
    ports:
      - "3338:3338"
    volumes:
      - lnd-data:/root/.lnd:ro
      - cashu-data:/app/data
    depends_on:
      - lnd
    networks:
      - merchant
'
fi

cat > "$COMPOSE_FILE" <<EOF
# ArxMint Merchant Node — ${MERCHANT_NAME}
# Generated by merchant-init.sh
# Run: docker compose -f ${COMPOSE_FILE} up -d

services:

  lnd:
    image: lightninglabs/lnd:v0.18.0-beta
    container_name: ${MERCHANT_SLUG}-lnd
    restart: unless-stopped
    command: >
      lnd
      --bitcoin.active
      --bitcoin.testnet
      --bitcoin.node=neutrino
      --neutrino.addpeer=faucet.lightning.community
      --rpclisten=0.0.0.0:10009
      --restlisten=0.0.0.0:8080
      --tlsextradomain=lnd
      --accept-keysend
      --db.backend=sqlite
    ports:
      - "9735:9735"
      - "10009:10009"
      - "8080:8080"
    volumes:
      - lnd-data:/root/.lnd
    networks:
      - merchant

  arxmint:
    image: ghcr.io/arxmint/arxmint:latest
    container_name: ${MERCHANT_SLUG}-app
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    environment:
      - LND_REST_ENDPOINT=https://lnd:8080
      - LND_TLS_CERT_PATH=/root/.lnd/tls.cert
      - LND_MACAROON_PATH=/root/.lnd/data/chain/bitcoin/testnet/admin.macaroon
    ports:
      - "3000:3000"
    volumes:
      - lnd-data:/root/.lnd:ro
    depends_on:
      - lnd
    networks:
      - merchant
${CASHU_SERVICE}
volumes:
  lnd-data:
  cashu-data:

networks:
  merchant:
    driver: bridge
EOF

echo "  Created $COMPOSE_FILE"
echo ""

# ── Summary ──────────────────────────────────────────────────
echo "========================================"
echo " Setup complete!"
echo "========================================"
echo ""
echo "  Merchant : ${MERCHANT_NAME}"
echo "  Payments : ${PAYMENT_LABEL}"
echo "  Domain   : ${DOMAIN}"
echo "  Network  : testnet (edit ${ENV_FILE} to change)"
echo ""
echo "  Secrets written to ${ENV_FILE}:"
echo "    CASHU_PRIVATE_KEY  = $(mask "$CASHU_PRIVATE_KEY")"
echo "    MACAROON_ROOT_KEY  = $(mask "$MACAROON_ROOT_KEY")"
echo "    NEXTAUTH_SECRET    = $(mask "$NEXTAUTH_SECRET")"
echo ""
echo "========================================"
echo " IMPORTANT — before you continue"
echo "========================================"
echo ""
echo "  1. Back up ${ENV_FILE} to a secure location."
echo "     Losing CASHU_PRIVATE_KEY means ecash wallet recovery"
echo "     is impossible."
echo ""
echo "  2. NEVER commit ${ENV_FILE} to git."
echo "     Verify it is in your .gitignore."
echo ""
echo "  3. After starting the stack, create the LND wallet:"
echo "       docker exec ${MERCHANT_SLUG}-lnd lncli create"
echo "     Save the 24-word seed phrase offline."
echo ""
echo "========================================"
echo " Start your node:"
echo "========================================"
echo ""
echo "  docker compose -f ${COMPOSE_FILE} up -d"
echo ""
echo "  Your checkout page will be at:"
if [ "$DOMAIN" = "localhost" ]; then
  echo "  http://localhost:3000/pay/${MERCHANT_SLUG}"
else
  echo "  https://${DOMAIN}/pay/${MERCHANT_SLUG}"
fi
echo ""
