#!/usr/bin/env bash
# ArxMint Merchant Init v1.1.0
# Three questions → live merchant node
# ============================================================
# ArxMint — Merchant Node Initializer
# 4 questions → .env + docker-compose.merchant.yml
# Usage: bash scripts/merchant-init.sh
#        curl -fsSL https://arxmint.com/scripts/merchant-init.sh | bash
# ============================================================

set -euo pipefail

ENV_FILE=".env.merchant"
COMPOSE_FILE="docker-compose.merchant.yml"

echo "========================================"
echo " ArxMint — Merchant Node Setup"
echo " Financial privacy as a human right."
echo "========================================"
echo ""

# ── Preflight: Docker check ──────────────────────────────────
if ! command -v docker &>/dev/null; then
  echo "ERROR: Docker is not installed."
  echo ""
  echo "Install Docker first:"
  echo "  https://docs.docker.com/engine/install/"
  exit 1
fi

if ! docker compose version &>/dev/null 2>&1; then
  echo "ERROR: 'docker compose' (v2) is not available."
  echo "Upgrade Docker Desktop or install the compose plugin."
  exit 1
fi

# ── Idempotency guard ────────────────────────────────────────
if [ -f "$ENV_FILE" ] || [ -f "$COMPOSE_FILE" ]; then
  echo "Existing config detected:"
  [ -f "$ENV_FILE" ]     && echo "  - $ENV_FILE"
  [ -f "$COMPOSE_FILE" ] && echo "  - $COMPOSE_FILE"
  echo ""
  printf "Re-running will overwrite these files. Continue? [y/N] "
  read -r REPLY
  echo ""
  if [[ ! "$REPLY" =~ ^[Yy]$ ]]; then
    echo "Aborted. Your existing config was not changed."
    exit 0
  fi
fi

# ── Question 1: Merchant name ────────────────────────────────
echo "Question 1 of 4"
printf "What is your merchant name? "
read -r MERCHANT_NAME
MERCHANT_NAME="${MERCHANT_NAME:-My Bitcoin Store}"

# Derive a slug: lowercase, replace spaces/special chars with hyphens
MERCHANT_SLUG=$(echo "$MERCHANT_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/-\+/-/g' | sed 's/^-//' | sed 's/-$//')
echo ""

# ── Question 2: Payment methods ──────────────────────────────
echo "Question 2 of 4"
echo "What payment methods do you want to accept?"
echo "  [1] lightning          — Lightning Network (recommended)"
echo "  [2] lightning + cashu  — Lightning + private ecash (default)"
echo "  [3] all                — Lightning + Cashu + on-chain Bitcoin"
printf "Choice [1/2/3, default 2]: "
read -r PAY_CHOICE
PAY_CHOICE="${PAY_CHOICE:-2}"
echo ""

case "$PAY_CHOICE" in
  1)
    ENABLE_CASHU=false
    ENABLE_ONCHAIN=false
    PAYMENT_LABEL="Lightning"
    ;;
  3)
    ENABLE_CASHU=true
    ENABLE_ONCHAIN=true
    PAYMENT_LABEL="Lightning + Cashu + On-chain"
    ;;
  *)
    ENABLE_CASHU=true
    ENABLE_ONCHAIN=false
    PAYMENT_LABEL="Lightning + Cashu"
    ;;
esac

# ── Question 3: Domain ───────────────────────────────────────
echo "Question 3 of 4"
printf "What domain/hostname will this run on? [localhost]: "
read -r DOMAIN
DOMAIN="${DOMAIN:-localhost}"
echo ""

# ── Question 4: Bitcoin network ──────────────────────────────
echo "Question 4 of 4"
echo "Which Bitcoin network?"
echo "  [1] testnet  (default — no real funds)"
echo "  [2] signet   (developer signaling network)"
echo "  [3] mainnet  (real Bitcoin)"
printf "Choice [1/2/3, default 1]: "
read -r NET_CHOICE
NET_CHOICE="${NET_CHOICE:-1}"
echo ""

case "$NET_CHOICE" in
  2)
    BITCOIN_NETWORK="signet"
    LND_NETWORK_FLAG="--bitcoin.signet"
    NETWORK_LABEL="signet"
    ;;
  3)
    BITCOIN_NETWORK="bitcoin"
    LND_NETWORK_FLAG="--bitcoin.mainnet"
    NETWORK_LABEL="mainnet"
    echo "========================================"
    echo " ⚠ MAINNET — real funds at risk."
    echo " Ensure you have channel backups."
    echo "========================================"
    echo ""
    ;;
  *)
    BITCOIN_NETWORK="testnet"
    LND_NETWORK_FLAG="--bitcoin.testnet"
    NETWORK_LABEL="testnet"
    ;;
esac

# ── Generate secrets ─────────────────────────────────────────
if ! command -v openssl &>/dev/null; then
  echo "ERROR: openssl is not installed. Required for secret generation."
  echo "  Ubuntu/Debian: sudo apt install openssl"
  echo "  macOS:         brew install openssl"
  exit 1
fi

CASHU_PRIVATE_KEY=$(openssl rand -hex 32)
MACAROON_ROOT_KEY=$(openssl rand -hex 32)
NEXTAUTH_SECRET=$(openssl rand -base64 32)

mask() { local val="$1"; echo "${val:0:4}****"; }

# ── Write .env.merchant ──────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# ArxMint Merchant Node — generated by merchant-init.sh
# NEVER commit this file to version control.

MERCHANT_NAME="${MERCHANT_NAME}"
MERCHANT_SLUG="${MERCHANT_SLUG}"
MERCHANT_DOMAIN="${DOMAIN}"

# Bitcoin network (testnet | signet | bitcoin)
# Change to 'bitcoin' when ready for mainnet real sats.
BITCOIN_NETWORK=${BITCOIN_NETWORK}

# Cashu ecash mint private key — BACK THIS UP
# Losing this key means wallet recovery is impossible.
CASHU_PRIVATE_KEY=${CASHU_PRIVATE_KEY}

# LND macaroon root key
MACAROON_ROOT_KEY=${MACAROON_ROOT_KEY}

# ArxMint web app session secret
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# Features
ENABLE_CASHU=${ENABLE_CASHU}
ENABLE_ONCHAIN=${ENABLE_ONCHAIN}
EOF

echo "  Created $ENV_FILE"

# ── Write docker-compose.merchant.yml ───────────────────────
CASHU_SERVICE=""
if [ "$ENABLE_CASHU" = "true" ]; then
  CASHU_SERVICE='
  cashu-mint:
    image: cashubtc/nutshell:latest
    container_name: '${MERCHANT_SLUG}'-cashu
    restart: unless-stopped
    environment:
      - MINT_BACKEND_BOLT11_SAT=LndRestWallet
      - MINT_LND_REST_ENDPOINT=https://lnd:8080
      - MINT_LND_REST_CERT=/root/.lnd/tls.cert
      - MINT_LND_REST_MACAROON=/root/.lnd/data/chain/bitcoin/${BITCOIN_NETWORK:-testnet}/admin.macaroon
      - MINT_LISTEN_HOST=0.0.0.0
      - MINT_LISTEN_PORT=3338
      - MINT_PRIVATE_KEY=${CASHU_PRIVATE_KEY}
    ports:
      - "3338:3338"
    volumes:
      - lnd-data:/root/.lnd:ro
      - cashu-data:/app/data
    depends_on:
      - lnd
    networks:
      - merchant
'
fi

cat > "$COMPOSE_FILE" <<EOF
# ArxMint Merchant Node — ${MERCHANT_NAME}
# Generated by merchant-init.sh
# Run: docker compose -f ${COMPOSE_FILE} up -d

services:

  lnd:
    image: lightninglabs/lnd:v0.18.0-beta
    container_name: ${MERCHANT_SLUG}-lnd
    restart: unless-stopped
    command: >
      lnd
      --bitcoin.active
      ${LND_NETWORK_FLAG}
      --bitcoin.node=neutrino
      --neutrino.addpeer=faucet.lightning.community
      --rpclisten=0.0.0.0:10009
      --restlisten=0.0.0.0:8080
      --tlsextradomain=lnd
      --accept-keysend
      --db.backend=sqlite
    ports:
      - "9735:9735"
      - "10009:10009"
      - "8080:8080"
    volumes:
      - lnd-data:/root/.lnd
    networks:
      - merchant

  arxmint:
    image: ghcr.io/arxmint/arxmint:latest
    container_name: ${MERCHANT_SLUG}-app
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    environment:
      - LND_REST_ENDPOINT=https://lnd:8080
      - LND_TLS_CERT_PATH=/root/.lnd/tls.cert
      - LND_MACAROON_PATH=/root/.lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/admin.macaroon
      - LSP_URL=\${LSP_URL:-}
      - CLOUDFLARE_API_TOKEN=\${CLOUDFLARE_API_TOKEN:-}
      - CLOUDFLARE_ZONE_ID=\${CLOUDFLARE_ZONE_ID:-}
    ports:
      - "3000:3000"
    volumes:
      - lnd-data:/root/.lnd:ro
    depends_on:
      - lnd
    networks:
      - merchant
${CASHU_SERVICE}
  # Optional: Cloudflare Tunnel for public reachability.
  # Set CF_TUNNEL_TOKEN in .env.merchant to activate.
  # Get a token: cloudflared tunnel create ${MERCHANT_SLUG}
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ${MERCHANT_SLUG}-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=\${CF_TUNNEL_TOKEN:-}
    networks:
      - merchant
    profiles:
      - tunnel
volumes:
  lnd-data:
  cashu-data:

networks:
  merchant:
    driver: bridge
EOF

echo "  Created $COMPOSE_FILE"
echo ""

# ── Summary ──────────────────────────────────────────────────
echo "========================================"
echo " Setup complete!"
echo "========================================"
echo ""
echo "  Merchant : ${MERCHANT_NAME}"
echo "  Payments : ${PAYMENT_LABEL}"
echo "  Domain   : ${DOMAIN}"
echo "  Network  : ${NETWORK_LABEL}"
echo ""
echo "  Secrets written to ${ENV_FILE}:"
echo "    CASHU_PRIVATE_KEY  = $(mask "$CASHU_PRIVATE_KEY")"
echo "    MACAROON_ROOT_KEY  = $(mask "$MACAROON_ROOT_KEY")"
echo "    NEXTAUTH_SECRET    = $(mask "$NEXTAUTH_SECRET")"
echo ""
echo "========================================"
echo " IMPORTANT — before you continue"
echo "========================================"
echo ""
echo "  1. Back up ${ENV_FILE} to a secure location."
echo "     Losing CASHU_PRIVATE_KEY means ecash wallet recovery"
echo "     is impossible."
echo ""
echo "  2. NEVER commit ${ENV_FILE} to git."
echo "     Verify it is in your .gitignore."
echo ""
echo "  3. After starting the stack, create the LND wallet:"
echo "       docker exec ${MERCHANT_SLUG}-lnd lncli create"
echo "     Save the 24-word seed phrase offline."
echo ""

# ── Compute URLs once ────────────────────────────────────────
if [ "$DOMAIN" = "localhost" ]; then
  CHECKOUT_URL="http://localhost:3000/pay/${MERCHANT_SLUG}"
  DASHBOARD_URL="http://localhost:3000/merchant"
  LIGHTNING_ADDR="${MERCHANT_SLUG}@localhost"
else
  CHECKOUT_URL="https://${DOMAIN}/pay/${MERCHANT_SLUG}"
  DASHBOARD_URL="https://${DOMAIN}/merchant"
  LIGHTNING_ADDR="${MERCHANT_SLUG}@pay.${DOMAIN}"
fi

# ── Post-setup validation: offer to start the stack ──────────
if command -v docker &>/dev/null; then
  echo ""
  printf "Ready to start your merchant node? [Y/n] "
  read -r START_REPLY
  START_REPLY="${START_REPLY:-Y}"
  echo ""

  if [[ "$START_REPLY" =~ ^[Yy]$ ]]; then
    echo "Starting stack..."
    docker compose -f "${COMPOSE_FILE}" --env-file "${ENV_FILE}" up -d

    echo ""
    echo "Waiting for health check (up to 60s)..."
    HEALTHY=false
    for i in $(seq 1 12); do
      if curl -sf http://localhost:3000/api/health > /dev/null 2>&1; then
        HEALTHY=true
        break
      fi
      sleep 5
    done

    if [ "$HEALTHY" = "true" ]; then
      echo "  ✅ Health check passed!"
      echo ""
      echo "  Checkout live at: ${CHECKOUT_URL}"
    else
      echo "  ⏳ Health check did not pass within 60s."
      echo "  The stack may still be starting. Check logs:"
      echo "    docker compose -f ${COMPOSE_FILE} logs -f"
    fi
    echo ""
  fi
fi

# ── Optional: Inbound Lightning liquidity (LSP bootstrap) ────
echo "========================================"
echo " Optional: Inbound Liquidity"
echo "========================================"
echo ""
echo "  New Lightning nodes have no inbound capacity."
echo "  Without it, you cannot receive payments."
echo ""
printf "  Set up automatic inbound liquidity? [Y/n] "
read -r LSP_REPLY
LSP_REPLY="${LSP_REPLY:-Y}"
echo ""

if [[ "$LSP_REPLY" =~ ^[Yy]$ ]]; then
  printf "  Your LND node public key (run 'lncli getinfo' after start): "
  read -r LND_NODE_ID
  echo ""
  if [ -n "$LND_NODE_ID" ]; then
    # Append LSP_URL to .env.merchant so the app knows the LSP endpoint
    if ! grep -q "LSP_URL" "$ENV_FILE" 2>/dev/null; then
      echo "" >> "$ENV_FILE"
      echo "# LSP liquidity bootstrap (see /api/lsp/bootstrap)" >> "$ENV_FILE"
      echo "LSP_URL=${LSP_URL:-https://lsp.voltage.cloud}" >> "$ENV_FILE"
    fi
    echo "  After your stack starts, bootstrap liquidity with:"
    echo "    curl -X POST http://localhost:3000/api/lsp/bootstrap \\"
    echo "         -H 'Content-Type: application/json' \\"
    echo "         -d '{\"nodeId\":\"${LND_NODE_ID}\"}'"
    echo ""
    echo "  Or visit: http://localhost:3000/merchant/setup"
  else
    echo "  Skipped — run the liquidity step after your LND wallet is created."
    echo "  Command: docker exec ${MERCHANT_SLUG}-lnd lncli getinfo"
  fi
fi

# ── Optional: Public URL via Cloudflare Tunnel ───────────────
echo ""
echo "========================================"
echo " Optional: Public URL (Cloudflare Tunnel)"
echo "========================================"
echo ""
echo "  Expose your node to the internet so customers can reach"
echo "  your checkout page from anywhere — no port forwarding needed."
echo ""
printf "  Set up a public URL? [Y/n] "
read -r CF_REPLY
CF_REPLY="${CF_REPLY:-Y}"
echo ""

if [[ "$CF_REPLY" =~ ^[Yy]$ ]]; then
  if command -v cloudflared &>/dev/null; then
    echo "  cloudflared detected. Creating tunnel..."
    cloudflared tunnel login 2>/dev/null || true
    cloudflared tunnel create "${MERCHANT_SLUG}" 2>/dev/null && \
      echo "  Tunnel created: ${MERCHANT_SLUG}" || \
      echo "  Could not create tunnel automatically."
    echo ""
    echo "  Run this to start the tunnel:"
    echo "    cloudflared tunnel run ${MERCHANT_SLUG}"
    echo ""
    echo "  Your public checkout URL will be:"
    echo "    https://${MERCHANT_SLUG}.arxmint.com/pay/${MERCHANT_SLUG}"
  else
    echo "  cloudflared not found. Install it first:"
    echo "    https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
    echo ""
    echo "  Then run:"
    echo "    cloudflared tunnel login"
    echo "    cloudflared tunnel create ${MERCHANT_SLUG}"
    echo "    cloudflared tunnel run ${MERCHANT_SLUG}"
  fi
fi

# ── Final summary banner ─────────────────────────────────────
echo ""
echo "========================================"
echo " 🏪 Your merchant node is ready!"
echo "========================================"
echo " Checkout:  ${CHECKOUT_URL}"
echo " Dashboard: ${DASHBOARD_URL}"
echo " API Keys:  ./scripts/arxmint.sh keys list --merchant-id ${MERCHANT_SLUG}"
echo ""
echo " Next steps:"
echo " 1. Fund your Lightning node (min 100K sats inbound)"
echo " 2. Test a checkout at the URL above"
echo " 3. Share your Lightning Address: ${LIGHTNING_ADDR}"
echo "========================================"
echo ""
